export { API_CONFIG } from './config';
export {
	api,
	login,
	register,
	logout,
	getEstablishments,
	getEstablishment,
	getCoffeeTrail,
	getCoffeeTrailHistory,
	getCouponPromos,
	verifyCouponPromoQr,
	getProducts,
	placeOrder,
	getMyOrders,
	updateOrderStatus,
	submitRating,
	getRatingsFeed,
	getMessages,
	sendMessage,
	getProfile,
	updateProfile,
	authService,
} from './api';
